import type { FormDefinition } from "@/types/form";

export const assessmentForm: FormDefinition = {
  form_metadata: {
    form_title: "D2C Internal Process Optimization - Initial Assessment",
    form_description:
      "Help us understand your daily workflows and pain points so we can build the most valuable automation tools in the next 90 days.\n\nEstimated time: 10-15 minutes\nYour feedback will directly influence tool development priorities.",
    created_by: "Han Wu - AI Automation Engineer",
    created_date: "2026-02-12",
    version: "1.0",
    form_type: "self-created forms",
    response_settings: {
      allow_anonymous: true,
      one_response_per_person: false,
      accept_responses: true,
      show_progress_bar: true,
      shuffle_questions: false,
    },
  },
  sections: [
    {
      section_id: "section_1",
      section_title: "Basic Information",
      section_description: "Tell us about your role",
      questions: [
        {
          question_id: "q1",
          question_text: "What is your role at D2C?",
          question_type: "choice",
          required: true,
          allow_multiple: false,
          options: [
            "Management",
            "Project Manager (PM)",
            "Estimator",
            "Operations Manager",
            "Finance/Accounting",
            "Foreman/Site Supervisor/Superintendent",
            "Other",
          ],
          has_other_option: true,
          points: 0,
        },
        {
          question_id: "q2",
          question_text: "Your name",
          question_type: "text",
          required: true,
          subtitle:
            "If left blank, this will be automatically recorded as Anonymous. Providing your name helps with follow-up discussions.",
          long_answer: false,
          points: 0,
        },
      ],
    },
    {
      section_id: "section_2",
      section_title: "Current Workflows",
      section_description: "Help us understand how you work today",
      questions: [
        {
          question_id: "q3",
          question_text: "What are the top 3 tasks you spend the most time on daily/weekly?",
          question_type: "text",
          required: true,
          long_answer: true,
          subtitle:
            "Please be specific and estimate time for each.\n\nExample:\n- Organizing site logs and entering into Excel (5 hours/week)\n- Searching for historical bid pricing (3 hours/week)\n- Preparing monthly progress billing (8 hours/month)",
          points: 0,
          priority: "high",
        },
        {
          question_id: "q4",
          question_text: "Which tools/systems do you currently use? (Select all that apply)",
          question_type: "choice",
          required: true,
          allow_multiple: true,
          options: [
            "Microsoft Excel",
            "Microsoft Word",
            "Microsoft Teams",
            "Microsoft Outlook",
            "SharePoint",
            "QuickBooks Desktop",
            "SiteMax",
            "Paper forms",
            "Other",
          ],
          has_other_option: true,
          points: 0,
          priority: "medium",
        },
        {
          question_id: "q5",
          question_text: "Do you frequently need to copy-paste data between different systems?",
          question_type: "choice",
          required: true,
          allow_multiple: false,
          options: ["Almost daily", "Several times per week", "Occasionally", "Rarely"],
          points: 0,
          priority: "high",
        },
        {
          question_id: "q6",
          question_text: "If yes, please describe a typical example",
          question_type: "text",
          required: false,
          long_answer: true,
          conditional_on: {
            question_id: "q5",
            condition: "not_equal",
            value: "Rarely",
          },
          subtitle:
            "Example: 'I export daily logs from SiteMax to Excel, then copy hours to QuickBooks timesheets, then paste into our progress summary. Takes about 1 hour.'",
          points: 0,
          priority: "high",
        },
      ],
    },
    {
      section_id: "section_3",
      section_title: "Pain Points Identification",
      section_description: "What is slowing you down?",
      questions: [
        {
          question_id: "q7",
          question_text: "What is the most time-consuming and repetitive task in your work?",
          question_type: "text",
          required: true,
          long_answer: true,
          subtitle:
            "Describe tasks that:\n- You repeat frequently\n- Are error-prone\n- Feel like 'should be automated'\n\nExample: 'At month-end, I manually consolidate labor hours from 10 project Excel sheets. Formula errors are common and require rework.'",
          points: 0,
          priority: "critical",
        },
        {
          question_id: "q8",
          question_text: "How often do you need to search for data or find historical files?",
          question_type: "choice",
          required: true,
          allow_multiple: false,
          options: ["Daily", "Several times per week", "Occasionally", "Rarely"],
          points: 0,
          priority: "high",
        },
        {
          question_id: "q9",
          question_text: "If yes, what are you typically searching for? (Select all that apply)",
          question_type: "choice",
          required: false,
          allow_multiple: true,
          conditional_on: {
            question_id: "q8",
            condition: "not_equal",
            value: "Rarely",
          },
          options: [
            "Historical Bid",
            "Project cost data",
            "Specification/Scope",
            "Daily log data",
            "Contract terms",
            "Supplier quotes",
            "Site photos",
            "Other",
          ],
          has_other_option: true,
          points: 0,
          priority: "high",
        },
        {
          question_id: "q10",
          question_text: "In your workflow, which step is most error-prone?",
          question_type: "text",
          required: true,
          long_answer: true,
          subtitle:
            "Examples:\n- Manual calculations lead to errors\n- Forgetting to update certain spreadsheets\n- Version confusion (not sure which is latest)\n- Data entry mistakes",
          points: 0,
          priority: "critical",
        },
      ],
    },
    {
      section_id: "section_4",
      section_title: "Specific Scenario Needs",
      section_description: "Deep dive into key workflows",
      questions: [
        {
          question_id: "q11",
          question_text:
            "[Bidding] When receiving a new bid, what information would you like to get automatically? (Select all that apply)",
          question_type: "choice",
          required: false,
          allow_multiple: true,
          subtitle: "Skip if you do not work on bidding",
          options: [
            "Historical similar project pricing and actual costs",
            "Auto-extracted scope and quantities from PDF",
            "Risk keyword identification (asbestos, tight deadline, etc.)",
            "Client payment history",
            "Suggested bid price range",
            "Similar project lessons learned",
            "Other",
          ],
          has_other_option: true,
          points: 0,
          priority: "high",
        },
        {
          question_id: "q12",
          question_text: "[Site Logs] What would your ideal site logging system look like?",
          question_type: "text",
          required: false,
          long_answer: true,
          subtitle:
            "Skip if you do not deal with site logs.\n\nExample:\n- Field workers fill on mobile directly\n- Auto-links to project and cost codes\n- PM sees real-time progress\n- Data flows directly to monthly billing",
          points: 0,
          priority: "high",
        },
        {
          question_id: "q13",
          question_text:
            "[Progress Billing] When preparing monthly progress invoices, what is the most painful part?",
          question_type: "text",
          required: false,
          long_answer: true,
          subtitle:
            "Skip if not applicable.\n\nExamples:\n- Collecting and organizing labor hours\n- Calculating completion percentages\n- Preparing backup documentation\n- Verifying data matches across systems",
          points: 0,
          priority: "high",
        },
        {
          question_id: "q14",
          question_text:
            "[Reports] What reports or data would you like to receive automatically each day/week? (Select all that apply)",
          question_type: "choice",
          required: false,
          allow_multiple: true,
          options: [
            "Project progress summary (all projects on one page)",
            "Labor hours and cost comparison (budget vs actual)",
            "Equipment utilization rates",
            "Safety incident tracking",
            "Accounts receivable reminders",
            "Change order status tracking",
            "Cash flow forecast",
            "Other",
          ],
          has_other_option: true,
          points: 0,
          priority: "medium",
        },
      ],
    },
    {
      section_id: "section_5",
      section_title: "AI and Automation Expectations",
      section_description: "Your thoughts on AI tools",
      questions: [
        {
          question_id: "q15",
          question_text: "How familiar are you with AI tools?",
          question_type: "choice",
          required: true,
          allow_multiple: false,
          options: [
            "Frequent user (e.g., ChatGPT, Perplexity/Gemini)",
            "Heard of it, tried occasionally",
            "Heard of it, never used",
            "Completely new to me",
          ],
          points: 0,
          priority: "medium",
        },
        {
          question_id: "q16",
          question_text: "What would you want AI to help you with? (Select all that apply)",
          question_type: "choice",
          required: true,
          allow_multiple: true,
          options: [
            "Auto-summarize long documents (contracts, specs)",
            "Extract key information from PDFs",
            "Predict costs based on historical data",
            "Auto-generate work descriptions (e.g., invoice descriptions)",
            "Answer questions about historical projects (chatbot)",
            "Identify issues in photos (e.g., safety hazards)",
            "Auto-fill forms based on previous data",
            "Other",
          ],
          has_other_option: true,
          points: 0,
          priority: "high",
        },
        {
          question_id: "q17",
          question_text: "Do you have any concerns about automation/AI?",
          question_type: "text",
          required: false,
          long_answer: true,
          subtitle:
            "We want AI to be an assistant, not a replacement. Please share honest concerns.\n\nExamples:\n- Worried about data accuracy\n- Concerned system will be too complex\n- Worried about losing control over processes",
          points: 0,
          priority: "medium",
        },
      ],
    },
    {
      section_id: "section_6",
      section_title: "Priorities and Expectations",
      section_description: "Help us focus on what matters most",
      questions: [
        {
          question_id: "q18",
          question_text: "If you could only have ONE automation tool, what would it be?",
          question_type: "choice",
          required: true,
          allow_multiple: false,
          options: [
            "Daily site log auto-consolidation",
            "Bid risk analysis assistant",
            "Progress billing auto-preparation",
            "Intelligent document search (find historical data)",
            "Real-time project cost dashboard",
            "Equipment maintenance tracking",
            "Other",
          ],
          has_other_option: true,
          points: 0,
          priority: "critical",
        },
        {
          question_id: "q19",
          question_text: "How much time are you willing to invest in learning and testing new tools?",
          question_type: "choice",
          required: true,
          allow_multiple: false,
          options: [
            "Happy to invest time if it improves efficiency",
            "Can accept 1-2 hours of training",
            "Want it very simple, no training needed",
            "Honestly, my schedule is very tight",
          ],
          points: 0,
          priority: "high",
        },
        {
          question_id: "q20",
          question_text: "Any other suggestions or expectations about automation tool development?",
          question_type: "text",
          required: false,
          long_answer: true,
          subtitle:
            "Examples:\n- Want tools to work on mobile\n- Need offline capability\n- Keep it simple, not too complex\n- Any other ideas",
          points: 0,
          priority: "medium",
        },
      ],
    },
  ],
  thank_you_message: {
    title: "Thank you for your time and feedback!",
    message:
      "Your input will directly influence tool development priorities over the next few months.\n\nI will share initial solution prototypes with you in the coming weeks.\n\nIf you would like to discuss any details further, please reach out via Teams or email anytime.\n\n- Han Wu\n  AI Automation Engineer\n  hancolinwu@outlook.com",
  },
  analysis_instructions: {
    priority_scoring: {
      critical: ["q7", "q10", "q18"],
      high: ["q3", "q5", "q6", "q8", "q9", "q11", "q12", "q13", "q16", "q19"],
      medium: ["q4", "q14", "q15", "q17", "q20"],
    },
    key_metrics: [
      "Most frequently mentioned pain points",
      "Most requested automation features",
      "Time spent on repetitive tasks",
      "System integration pain points",
      "AI familiarity level distribution",
    ],
    output_format: {
      excel_analysis: true,
      power_bi_dashboard: false,
      summary_report: true,
    },
  },
};

